staff = [
  "BORIS",
  "BORAT",
  "JOHAN",
  "CLAUS",
  "IRIS",
  "ADA",
  "ZARA",
  "XENO",
]

bookingName = [
  "Michelle",
  "Henry",
  "Sarah",
  "Stanhope",
  "Wisely",
  "Smith",
  "Andrew",
  "Arlo",
  "Gunther",
  "Jimtill",
  "Earnest",
  "Stevens",
  "Charlie",
  "Nyguen",
]

# variableContentKeys = [
#   "NAME:",
#   "TABLE NO",
#   "ORDER NUMBER",
#   "COVERS:",
# ]

docketStartFields = [
  # note: different from what is used in 'knuckle_dragger'.
  # there it is all capitalized
  "Restaurant Bar", 
  "TAB BAR",
  "JUKE BAR",
  "GAMING BAR",
  "SPORTS BAR",
]

courseFields = [
  "ENTREES DINNER",
  "MAINS DINNER",
  "MAINS LUNCH",
  "BAR MEALS",
  "CHILDS MENUS",
  "CHILD DESSERT TOPS",
  "DESSERT",
  "ADD MODIFIERS",
  "SPECIAL INSTRUCTIONS",
  "COFFEE TYPES",
  "SIDES"
]

callAwayDocket = {
  "course_field": "SPECIAL INSTRUCTIONS",
  "menu_item": "1    CALL AWAY",
  "info": ["1    go on mains"],
}

entrees = [
  "ARANCINI",
  "BREAD ROLL",
  "BRUSCHETTA",
  "BRUSCHETTA TOMAT",
  "CHILDS BOLOG",
  "CHILDS BURGER",
  "CHILDS FISH",
  "CHILDS HAMBURGER",
  "CHILDS PARMI",
  "CHILDS RICE",
  "CHILDS ROAST",
  "CHILDS SNIT",
  "CHILDS STEAK",
  "CALAMARI",
  "CHILLI CALAMARI",
  "GARLIC BREAD",
  "FALAFEL SMALL",
  "FRIES",
  "DUMPLINGS",
  "OYSTERS KIL 1",
  "OYSTERS NAT 1",
  "QUINOA SALAD",
  "SEN GARL BREAD",
  "SOUP OF THE DAY",
  "SOUP",
  "SWEET POT FRIES",
  "WEDGES",
]

mains =[
  "BARRAMUNDI",
  "BEEF BURGER",
  "BEEF SLIDERS",
  "BIRYANI CURRY",
  "BRISKET SAND",
  "CALAMARI",
  "CAULIFLOWER ALM",
  "CHICK RIBS",
  "CHICKEN BURGER",
  "CHILDS BOLOG",
  "CHILDS BURGER",
  "CHILDS FISH",
  "CHILDS HAMBURGER",
  "CHILDS PARMI",
  "CHILDS RICE",
  "CHILDS ROAST",
  "CHILDS SNIT",
  "CHILDS STEAK",
  "CHILLI CALAMARI",
  "CIGAR",
  "CRISPY CHIPS",
  "CRUMBED PRAWNS",
  "CUMIN CARROTS",
  "DUCK",
  "DUMPLINGS",
  "EYE FILLET 250GM",
  "FALAFEL SMALL",
  "FALAFEL LARGE",
  "FREEKAH FALAFEL",
  "FRIES",
  "GARLIC CHATS",
  "GARDEN SALAD",
  "GNOCCHI",
  "HAKE",
  "HANGER 200",
  "HANGER 400",
  "LOADED FRIES",
  "MAIN SPECIALS",
  "MARINATED CHIC",
  "NACHOS",
  "NASI",
  "PAPPADELLE LAMB",
  "PAPPARDELL LAMB",
  "PARMA",
  "PARMIGIANA",
  "POPCORN CHICK",
  "PORK BELLY",
  "PORK CUTLET",
  "PORK SLIDERS",
  "PORK TERRINE",
  "PORTER",
  "PORTERHOUSE 300",
  "PRAWN RISOTTO",
  "QUINOA SALAD",
  "ROAST",
  "ROAST VEG",
  "SALMON",
  "SALMON SALAD",
  "SCOTCH FILLET",
  "SCHNITZEL",
  "SENIOR FISH CHIP",
  "SENIOR ROAST",
  "SENIOR SNIT",
  "SENIOR SOUP",
  "SHARE JUKE ONE",
  "SHARE MEMBER TWO",
  "SOUP OF THE DAY",
  "SOUP",
  "SWEET POT FRIES",
  "TACOS",
  "TEXAN",
  "WAGU RUMP",
  "WEDGES",
  "WHITING",
  "WINTER GREENS",
  "WRAP",
]

# ANOMALOUS CONTENT ==> this is a worry.
anonymous = [
  "for the band",
  "add gravy",
  "EXTRA PEPP SAUCE"
]


desserts = [
  "AFFOGATO",
  "CAKE DISPLAY",
  "CARAMEL TOPPING",
  "CHEESE CAKE",
  "CHILDS FROG POND",
  "CHILDS ICE CREAM",
  "CHILDS MOUSSE",
  "CHOCO TOPPING",
  "CHURROS",
  "CREME CARAMEL",
  "DESSERT SPEC",
  "EXTRA ICECREAM",
  "FONDANT",
  "KIDS EXTRA DESS",
  "NO TOPPING",
  "OPEN FOOD",
  "SENIOR MOUSSE",
  "SENIOR PUDDING",
  "SENIOR SORBETS",
  "SPINKLES ONLY",
  "STICKY DATE PUDD",
  "STRAWB TOPPING",
]